### ISSUE TITLE
CT got defuse kit and an incendiary grenade during pistol round

### ISSUE THREAD

**Issue by borzaka** [shanapu/MyWeaponAllocator#15]
This shouldn't be possible, because it's 1000$

And probably related, still in pistol round sometimes I got desert eagle and a vest, which shouldn't be possible also.

Maybe this is wrong, and should be 600, as the incgrenade costs 600$ at the CT side.
https://github.com/shanapu/MyWeaponAllocator/blob/a92dcad82f8d898103bec0f8a4b049060efdb4d1/scripting/MyWeaponAllocator.sp#L1488-L1493

or change it to:
money -= `GetWeaponPrice("weapon_incgrenade");`

**Comment by shanapu** [comment]
thank you for all your support and work!
