### ISSUE TITLE
cant disable p90 and nova

### ISSUE THREAD

**Issue by flashing1998** [shanapu/MyWeaponAllocator#18]
i disabled p90 and nova for full buy rounds from the config but players are still getting them

**Comment by borzaka** [comment]
Unfortunately if someone has an enabled weapon that later is disabled, he will still could get that weapon.
Probably it's a bug.

Solutions:
- re enabled that weapons, and ask the guys who has them to disable in the !guns setting
- delete the clientpref sql - everyone has to set again everything
