### ISSUE TITLE
New update game csgo error color 19.11.2019

### ISSUE THREAD

**Issue by ByKyTa** [shanapu/MyWeaponAllocator#20]
![Uploading image.png…]()

**Comment by gabriel3l** [comment]
mywa_bombsite "0"
until it's fixed

**Comment by rpkaul** [comment]
[https://forums.alliedmods.net/showpost.php?p=2673590&postcount=5](url)

use this

**Comment by shmidtelson** [comment]
@rpkaul please, fix link
@ByKyTa please, fix image
@gabriel3l +1 temporary solution!

**Comment by shmidtelson** [comment]
Problem in 
https://github.com/shanapu/MyWeaponAllocator/blob/a92dcad82f8d898103bec0f8a4b049060efdb4d1/scripting/MyWeaponAllocator.sp#L652
Two variant:
1. https://github.com/shanapu/MyWeaponAllocator/issues/20#issuecomment-555731613 - use this or edit plugin by this solution.
2. fix code, removing html tags

**Comment by rpkaul** [comment]
@shmidtelson  sorry link fixed now

**Comment by shanapu** [comment]
Is this still a thing?
Did valve really removed the support for html (<font>) tags? 
Any other new solutions for colored hinttext?

havn't played custom csgo or made any sourcemod related since ages...

if so I have to rewrite this so no fix plugin is needed
