### ISSUE TITLE
SMG not work

### ISSUE THREAD

**Issue by chulicoxd** [shanapu/MyWeaponAllocator#21]
Hi, how are you? I have a small problem and the smg menu does not work for me, I have the splewis retake and its complement and the MyWeaponAllocator.cfg configuration is not generated according to the installation guide and nothing continues just by selecting of pistols rifles and awp

**Comment by chulicoxd** [comment]
I realized that I have this add-on also retakes_standardallocator.smx deleted this add-on so that yours that has smg works?

**Comment by borzaka** [comment]
Yes, you have to disable any other weapon allocator plugin, if you what to use this plugin. This includes the default retakes_standardallocator plugin as well.

**Comment by chulicoxd** [comment]
hello friend thanks for answering me I thought that would not happen. Disable the retakes_standardallocator.smx and install the add-on of you but it does not run, the restart continues to work perfectly but does not let me put the !guns menu. and when I rerun the retakes_standardallocator.smx the !guns menu works normally again but only pistols rifles and awp, smg / scout does not work

**Comment by chulicoxd** [comment]
These are the add-ons that I have without adding the MyWeaponAllocator do you see any other add-on other than the retakes_standardallocator.smx that can make a conflict?

![plugins](https://user-images.githubusercontent.com/60021173/73600113-bf617680-452a-11ea-8547-b18835f006bf.png)

and this is my version of sourcemod

![myversionsourcemod](https://user-images.githubusercontent.com/60021173/73600151-2aab4880-452b-11ea-95a4-872133a7346d.png)


[SM] Plugin myweaponallocator.smx is already loaded. 

being inside works retake normally but the weapons menu does not work! and with the server console I put sm_cvar mywa_enable "1" and I figure this in the console:
[SM] Unable to find cvar: mywa_enable

**Comment by borzaka** [comment]
There is no `MyWeaponAllocator.smx` in your plugins folder;
- Download this repository, and copy **all** the files to the correct folders.
- Move `retakes_standardallocator.smx` to the `disabled` folder, because it will conflict with _MyWeaponAllocator_.
- Restart your server. Always restart your servers if you make changes to the plugins and want to see the changes. You can load/unload plugins, but you look like a rookie, and it's easier for you to restart.

`retakes_autoplant.sp` shouldn't be there, `.sp` files belongs to` scripting` folder.

**Comment by chulicoxd** [comment]
Thank you very much you are very kind and I could make it work but I have one last problem and that is that I get a central message but it looks bad and when you remove it everything is unconfigured and it becomes full buy every round. What could I do?
![msgcentral](https://user-images.githubusercontent.com/60021173/73615128-14ad8e80-45e4-11ea-9b36-b149711a99f3.png)
![myweaponallocator1](https://user-images.githubusercontent.com/60021173/73615132-1aa36f80-45e4-11ea-811c-0e7f47b0c235.png)
![MyWeaponAllocator3](https://user-images.githubusercontent.com/60021173/73615167-5d654780-45e4-11ea-9d8d-9efffa2f7e42.png)

**Comment by borzaka** [comment]
That's a known problem; an update removed the support of HTML tags in alert messages.
You have to use this plugin to fix that: [FixHintColorMessages](https://github.com/Franc1sco/FixHintColorMessages)
Copy the `.smx` to the _plugins_ folder. You don't need the `.sp` file, but you can copy it to _scripting_.
Restart your server.

After that, the messages became styled again, but with a starting green `$`. That's the fix, don't complain about it.

**Comment by chulicoxd** [comment]
With that it solves everything for me !!! and it will be perfect! Thank you very much for taking your time to answer me!
