### ISSUE TITLE
Retakes text shows as HTML

### ISSUE THREAD

**Issue by cryptospook86** [shanapu/MyWeaponAllocator#24]
This plugin causes the text in hint tips to show as HTML, any way to fix this?

https://cdn.discordapp.com/attachments/292038238879744000/710156264478474290/unknown.png

![badfont](https://user-images.githubusercontent.com/44852771/81839042-017c5a00-9515-11ea-971b-613deffae22f.png)

**Comment by cryptospook86** [comment]
Issue caused by CSGO, fixed by using a different plugin to remove HTML Tagging.

**Comment by MLNW** [comment]
I have the same issue. Could you give a few more details how you fixed this @cryptospook86 ?

**Comment by cryptospook86** [comment]
https://github.com/Franc1sco/FixHintColorMessages

The issue is they removed support for HTML. The above fixed it.

**Comment by cryptospook86** [comment]
I fixed it by using this: https://github.com/Franc1sco/FixHintColorMessages
