### ISSUE TITLE
HTML like code in helper popup

### ISSUE THREAD

**Issue by ninkaninus** [shanapu/MyWeaponAllocator#28]
After i have installed your other wise perfect plugin i get this:
![image](https://user-images.githubusercontent.com/10107595/94858288-1f4e4b00-0433-11eb-852d-45c22b5007c0.png)

If it is not related to this plugin, can you point me in the right  direction?

**Comment by spacecow123** [comment]
https://github.com/Franc1sco/FixHintColorMessages

**Comment by ninkaninus** [comment]
thanks a lot, works perfectly
