### ISSUE TITLE
mp_restartgame has no effect on ascending rounds (pistol -> force -> full)

### ISSUE THREAD

**Issue by borzaka** [shanapu/MyWeaponAllocator#4]
If you reach to the full buy rounds, and execute `mp_restartgame x`, the full buy round continue instead of starting with pistol again.

_Edited: I meant `mp_restartgame x` insted of `mp_restartround x`_

**Comment by shanapu** [comment]
I will take a look at this, maybe need a while, have to find a smooth& sane way to hook `mp_restartgame`.
Stay tuned

**Comment by shanapu** [comment]
I added a match restart hook and reset the round counter. 
I pushed it to 'onlyServer' branch https://github.com/shanapu/MyWeaponAllocator/archive/onlyServer.zip . Couldn't test it very well. Please test.

**Comment by shanapu** [comment]
give this a new try.

**Comment by borzaka** [comment]
It's working: after `rcon mp_restartgame 1` a new pistol round started. Thank you.

**Comment by shanapu** [comment]
thanks!
I will merge this to master branch as new version soon.
