### ISSUE TITLE
Update for the new ecenomy

### ISSUE THREAD

**Issue by borzaka** [shanapu/MyWeaponAllocator#5]
> — In Competitive Matchmaking, both teams are now considered to start the half with a one-round ‘losing streak’ that is reset following a round win. Instead of $1400, the Round 1 loser receives $1900, then $2400 for a subsequent loss, etc.
[release note](http://blog.counter-strike.net/index.php/2018/10/21333/)

**Comment by shanapu** [comment]
Is this a request, an issue or just a notification? I don't get it.

**Comment by borzaka** [comment]
With the new losing-streak change, you would have $2700 (800 + 1900) in a force-buy round maximum.
> Instead of $1400, the Round 1 loser receives $1900, then $2400 for a subsequent loss, etc.

So I would change this to 2700:
https://github.com/shanapu/MyWeaponAllocator/blob/master/scripting/MyWeaponAllocator.sp#L147

**Comment by shanapu** [comment]
This is just the default value of the ConVar.
You can change it to "2700" or whatevery you want in the configs file: `/csgo/cfg/sourcemod/retakes/MyWeaponAllocator.cfg`

 I'll update the default value within the next commit. Not worth to commit just that.

**Comment by shanapu** [comment]
merged
