### ISSUE TITLE
Doesn't work whatsoever, am posting error messages.

### ISSUE THREAD

**Issue by kntrllr** [shanapu/MyWeaponAllocator#7]
L 01/03/2019 - 15:57:07: [SM] Exception reported: Language phrase "Pistol Round" not found (arg 5)
L 01/03/2019 - 15:57:07: [SM] Blaming: allocator.smx
L 01/03/2019 - 15:57:07: [SM] Call stack trace:
L 01/03/2019 - 15:57:07: [SM]   [0] Format
L 01/03/2019 - 15:57:07: [SM]   [1] Line 383, MyWeaponAllocator.sp::Event_RoundStart

L 01/03/2019 - 15:59:28: [SM] Exception reported: Language phrase "Select a T rifle" not found (arg 5)
L 01/03/2019 - 15:59:28: [SM] Blaming: allocator.smx
L 01/03/2019 - 15:59:28: [SM] Call stack trace:
L 01/03/2019 - 15:59:28: [SM]   [0] Format
L 01/03/2019 - 15:59:28: [SM]   [1] Line 515, MyWeaponAllocator.sp::Menu_Primary
L 01/03/2019 - 15:59:28: [SM]   [2] Line 334, MyWeaponAllocator.sp::Retakes_OnGunsCommand
L 01/03/2019 - 15:59:28: [SM]   [4] Call_Finish
L 01/03/2019 - 15:59:28: [SM]   [5] Line 337, ././scripting/retakes.sp::Command_Guns

**Comment by shanapu** [comment]
> L 01/03/2019 - 15:57:07: [SM] Exception reported: **Language phrase "Pistol Round" not found** (arg 5)
> L 01/03/2019 - 15:57:07: [SM] Blaming: **allocator.smx**
> L 01/03/2019 - 15:59:28: [SM] Exception reported: **Language phrase "Select a T rifle" not found** (arg 5)
> L 01/03/2019 - 15:59:28: [SM] Blaming: **allocator.smx**


You are missing the translation file or it is corrupted by edit.

Reinstall this file to your servers `./addons/sourcemod/translations/`
https://github.com/shanapu/MyWeaponAllocator/blob/master/translations/MyWeaponAllocator.phrases.txt

Also seems you edited a bit more, or don't use my original version. 
Your binary is named **allocator.smx** but it original **MyWeaponAllocator.smx**

**Comment by kntrllr** [comment]
Oh thanks, I do use your original version I just renamed the file. But, thanks for the solution
